If you prefer YAML, here’s how the same API description looks in this format:

yaml
openapi: "3.0.0"
info:
  title: "Tender API"
  version: "1.0"
  description: "API for fetching tender details"

paths:
  /tenders:
    get:
      summary: "Get all tenders"
      responses:
        200:
          description: "List of tenders"
          content:
            application/json:
              schema:
                type: object
                properties:
                  tenders:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        title:
                          type: string
                        deadline:
                          type: string
                          format: date